# Generated by Django 2.0 on 2020-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_list',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_test',
            },
        ),
    ]
